name: Kent2018_GametocyteDev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - altair
  - notebook
  - vega
  - bokeh
  - ipykernel
  - black
  - isort
 # - flake8 
  - pytest
  - pytest-cov
  - pre_commit